### ISSUE TITLE
Make sure sessions start at the first question of a deck

### ISSUE THREAD

**Issue by schu** [openmultiplechoice/openmultiplechoice#1053]
A user reported that sometimes sessions don't start at the first question of a deck, i.e. there appears to be an inconsistency or bug in how we order questions or in how we select the first question. To be investigated.

**Comment by levinuss** [comment]
I think this is because [this line in `SessionController.php`](https://github.com/openmultiplechoice/openmultiplechoice/blob/a95e8cae5553ace38ed06d1963fdb99ccdf37328/app/Http/Controllers/SessionController.php#L47) (also in `Api/SessionsController.php`) has no guaranteed ordering. Without a specified order the database [does not guarantee any order](https://dba.stackexchange.com/questions/5774/why-is-ssms-inserting-new-rows-at-the-top-of-a-table-not-the-bottom/5775#5775) (even though it usually is asc by id).

I could reproduce this behavior in `artisan tinker` by executing `App\Models\Session::find(session_id)->deck->questions->first();` multiple times (some times it fluked and got me different "first" questions).

I think we could resolve this by including a `->orderBy('id')` in the two affected queries or adding it to the `questions` relation in `Models/Deck.php`.
